version: '3.7'

services:
  spider:
    build: ./spider/
    volumes:
      - ./spider:/app
    env_file:
      - ./.env
  hawkeye:
    build: ./hawkeye/
    volumes:
      - ./hawkeye:/app
    env_file:
      - ./.env
  racoon:
    build: ./racoon/
    volumes:
      - ./racoon:/app
    env_file:
      - ./.env
  meerkat:
    build: ./meerkat/
    volumes:
      - ./meerkat:/app
    env_file:
      - ./.env